/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
/**
 *
 * @author Phellogen
 */
public class accounttype extends javax.swing.JFrame {
static String s,c,f,ID,IDU;
Connection conn;
PreparedStatement ps,ps1,ps2,ps3;
ResultSet rs;
    /**
     * Creates new form accounttype
     */
    public accounttype() {
        initComponents();
        conn = javaconnect.ConncerDB();
       // overlay.setBackground(new Color(0,0,0,100));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CurrentAmount = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnexit1 = new javax.swing.JLabel();
        btnexit2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 81, 181));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter your amount");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1110, 230));

        CurrentAmount.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        CurrentAmount.setForeground(new java.awt.Color(52, 52, 52));
        CurrentAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentAmount.setBorder(null);
        jPanel2.add(CurrentAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 440, 120));

        jSeparator3.setBackground(new java.awt.Color(52, 52, 52));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 440, 160));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkmini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel2.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 40, 40));

        btnexit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkexit.png"))); // NOI18N
        btnexit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit2MouseClicked(evt);
            }
        });
        jPanel2.add(btnexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 40, 40));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 160, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void btnexit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexit2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       
        try {
           String sql1 = "select * from Generator where Count='1'"; 
           ps  = conn.prepareStatement(sql1);
           rs = ps.executeQuery();
           if(rs.next()){
                
               
                ID = rs.getString("Current_Account");
           }
           ps.close();
           rs.close();
       } catch (Exception  e) {
           JOptionPane.showMessageDialog(null, e);
       }
        try{
              String c = CurrentAmount.getText();
              
             String add ="update  Customer_Data set Current_Amount='"+c+"' where ID='"+ID+"'";
            ps = conn.prepareStatement(add);
            ps.executeUpdate();
            ps.close();
            
            
        } catch (SQLException ex) {
        Logger.getLogger(accounttype.class.getName()).log(Level.SEVERE, null, ex);
    }
       
         
        IDU = "UB"+ID;
        
        System.out.print(IDU);
        String sql  = "update Customer_Data set ID='"+IDU+"'where ID ='"+ID+"' ";
        String sql1 = "update Interest_Data set ID='"+IDU+"' where ID ='"+ID+"'";
        String sql2 = "update Transfer_Data set ID='"+IDU+"' where ID ='"+ID+"'";
        String sql3 = "update Generator set Current_Account='"+IDU+"' where Count='1'";
    try {
        ps1 =conn.prepareStatement(sql1);
        ps2 = conn.prepareStatement(sql2);
        ps = conn.prepareStatement(sql);
        ps3= conn.prepareStatement(sql3);
        ps3.executeUpdate();
        ps1.executeUpdate();
        ps2.executeUpdate();
         ps.executeUpdate();
         ps.close();
    } 
    
   
    
    catch (SQLException ex) {
        Logger.getLogger(accounttype.class.getName()).log(Level.SEVERE, null, ex);
    }
                         JOptionPane.showMessageDialog(null,"Your ID is "+IDU);
                        userHome uhome=new userHome();
                        uhome.setVisible(true);
                        uhome.pack();
                        uhome.setLocationRelativeTo(null);
                        uhome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
       
    }//GEN-LAST:event_jButton1MouseClicked
   
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(232, 234, 246));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(255,255,255));
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accounttype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentAmount;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JLabel btnexit2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
