/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Phellogen
 */
public class adminhome extends javax.swing.JFrame {

    /**
     * Creates new form adminhome
     */
    public adminhome() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IDno = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        btnedit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JLabel();
        btnexit2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btndeposit = new javax.swing.JPanel();
        inddeposit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        depositicon2 = new javax.swing.JLabel();
        btnoverview = new javax.swing.JPanel();
        indoverview = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        historyicon = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(63, 81, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jhon");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 90, 40));

        IDno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        IDno.setForeground(new java.awt.Color(255, 255, 255));
        IDno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDno.setText("C0018");
        jPanel1.add(IDno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 90, 50));

        email.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        email.setText("jhon4233@gmail.com");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        btnedit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/edit.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/museradd.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 170, 210));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/mwhitemini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel1.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        btnexit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/mwhiteexit.png"))); // NOI18N
        btnexit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit2MouseClicked(evt);
            }
        });
        jPanel1.add(btnexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 210));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndeposit.setBackground(new java.awt.Color(255, 255, 255));
        btndeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndepositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndepositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndepositMouseExited(evt);
            }
        });
        btndeposit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inddeposit.setBackground(new java.awt.Color(233, 30, 99));
        btndeposit.add(inddeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 4));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 52, 52));
        jLabel5.setText("Deposit");
        btndeposit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("into customer bank account.");
        btndeposit.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Put the sum of money  ");
        btndeposit.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        depositicon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/deposit8.png"))); // NOI18N
        btndeposit.add(depositicon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 60, 130));

        jPanel4.add(btndeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 370, 280));

        btnoverview.setBackground(new java.awt.Color(255, 255, 255));
        btnoverview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnoverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoverviewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnoverviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnoverviewMouseExited(evt);
            }
        });
        btnoverview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indoverview.setBackground(new java.awt.Color(233, 30, 99));
        btnoverview.add(indoverview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 4));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 52, 52));
        jLabel7.setText("Overview");
        btnoverview.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        historyicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/Overview.png"))); // NOI18N
        btnoverview.add(historyicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 50, 120));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Manage all user data information");
        btnoverview.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("in one place.");
        btnoverview.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel4.add(btnoverview, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 370, 280));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Home");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Terms and conditions");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 130, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("About us");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, 30));

        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkback.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        jPanel4.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 40, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 930, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        adminlogin alogin=new adminlogin();
        alogin.setVisible(true);
        alogin.pack();
        alogin.setLocationRelativeTo(null);
        alogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btndepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseClicked
        deposit d=new deposit();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btndepositMouseClicked

    private void btndepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseEntered

        setColor(inddeposit);
        resetColor(indoverview);
       
    }//GEN-LAST:event_btndepositMouseEntered

    private void btndepositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseExited
        resetColor(inddeposit);
        resetColor(indoverview);
      

    }//GEN-LAST:event_btndepositMouseExited

    private void btnoverviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoverviewMouseEntered
        resetColor(inddeposit);
        setColor(indoverview);
      
    }//GEN-LAST:event_btnoverviewMouseEntered

    private void btnoverviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoverviewMouseExited
        resetColor(inddeposit);
        resetColor(indoverview);
       
    }//GEN-LAST:event_btnoverviewMouseExited

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void btnexit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexit2MouseClicked

    private void btnoverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoverviewMouseClicked
        overview o=new overview();
        o.setVisible(true);
        o.pack();
        o.setLocationRelativeTo(null);
        o.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnoverviewMouseClicked
    
     void setColor(JPanel panel)
    {
        panel.setBackground(new Color(233, 30, 99));
        
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(255,255,255));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDno;
    private javax.swing.JLabel btnback;
    private javax.swing.JPanel btndeposit;
    private javax.swing.JLabel btnedit;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JLabel btnexit2;
    private javax.swing.JPanel btnoverview;
    private javax.swing.JLabel depositicon2;
    private javax.swing.JLabel email;
    private javax.swing.JLabel historyicon;
    private javax.swing.JPanel inddeposit;
    private javax.swing.JPanel indoverview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
