/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import static banking.deposit.conn;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Phellogen
 */
public class deposit extends javax.swing.JFrame {

     static Connection conn;
        Statement stmt;
        PreparedStatement ps,ps1,ps2;
        ResultSet rs;
        static String show2,ID;

    public deposit() {
        initComponents();

        this.setLocationRelativeTo(null);
        conn=javaconnect.ConncerDB();
        date();
        time();
        String sql1 = "select * from Generator where Count='1'";
       try {
           ps  = conn.prepareStatement(sql1);
           rs = ps.executeQuery();
           if(rs.next()){

                id.setText(rs.getString("Current_Account"));
                ID = rs.getString("Current_Account");
           }
       } catch (SQLException ex) {
           Logger.getLogger(withdraw.class.getName()).log(Level.SEVERE, null, ex);
       }
         String sql="select * from Customer_Data where ID='"+ID+"'";
            try {
                ps = conn.prepareStatement(sql);

                rs = ps.executeQuery();
                if(rs.next()){
                show2 = rs.getString("Name");

                String show3= rs.getString("Current_Amount");
                amount.setText(show3);


                }
                //rs=stmt.executeQuery(sql);


            } catch (Exception e) {
                e.printStackTrace();
            }


    id.setEditable(false);

    amount.setEditable(false);
    time.setEditable(false);
    date.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deamount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnconfirm = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btncancel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnexit2 = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        btnback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setBackground(new java.awt.Color(225, 225, 225));
        jLabeltitle.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabeltitle.setForeground(new java.awt.Color(63, 81, 181));
        jLabeltitle.setText("Deposit");
        jPanel1.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 300, 160));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Enter your deposit ammount.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 260, -1));

        deamount.setBackground(new java.awt.Color(246, 246, 246));
        deamount.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        deamount.setBorder(null);
        deamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deamountActionPerformed(evt);
            }
        });
        jPanel1.add(deamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 300, 80));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 300, 20));

        btnconfirm.setBackground(new java.awt.Color(63, 81, 181));
        btnconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconfirmMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Confirm");

        javax.swing.GroupLayout btnconfirmLayout = new javax.swing.GroupLayout(btnconfirm);
        btnconfirm.setLayout(btnconfirmLayout);
        btnconfirmLayout.setHorizontalGroup(
            btnconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnconfirmLayout.setVerticalGroup(
            btnconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnconfirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 110, 50));

        btncancel.setBackground(new java.awt.Color(233, 30, 99));
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncancelMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cancel");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btncancelLayout = new javax.swing.GroupLayout(btncancel);
        btncancel.setLayout(btncancelLayout);
        btncancelLayout.setHorizontalGroup(
            btncancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btncancelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btncancelLayout.setVerticalGroup(
            btncancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btncancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        btnexit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkexit.png"))); // NOI18N
        btnexit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit2MouseClicked(evt);
            }
        });
        jPanel1.add(btnexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkmini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel1.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 820, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 50));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Amount");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Current ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 30));

        id.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(63, 81, 181));
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 50));

        amount.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        amount.setForeground(new java.awt.Color(63, 81, 181));
        amount.setBorder(null);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 190, 60));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Date");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 50));

        date.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(63, 81, 181));
        date.setBorder(null);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 190, 50));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Time");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, 50));

        time.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        time.setForeground(new java.awt.Color(63, 81, 181));
        time.setBorder(null);
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 190, 50));

        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkback.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

    }//GEN-LAST:event_idActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed

    }//GEN-LAST:event_amountActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void deamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deamountActionPerformed

    }//GEN-LAST:event_deamountActionPerformed

    private void btncancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseClicked

          deamount.setText("");

    }//GEN-LAST:event_btncancelMouseClicked

    private void btnconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseClicked


        try {
                String de=deamount.getText();
                int i=Integer.parseInt(de);
                String camount=amount.getText();
                int i1=Integer.parseInt(camount);
                int sum=i+i1;
                String sum1=String.valueOf(sum);
                String t = id.getText();
                amount.setText(sum1);
                String sql="update Customer_Data set CURRENT_AMOUNT='"+sum1+"'  where ID='"+t+"'";

                String sql2 = "insert into History (ID,Name,Type,Amount,Date,Time)values(?,?,?,?,?,?)";
                JOptionPane.showMessageDialog(this,"You have deposited "+de+" to your account successfully");
                ps2 = conn.prepareStatement(sql2);
                String text = new SimpleDateFormat("yyyy/MM/dd", Locale.FRANCE).format(new Date());
                String tt = time.getText();
                ps2.setString(1,t);
                ps2.setString(2,show2);
                ps2.setString(3,"Deposit");
                ps2.setString(4, de);
                ps2.setString(5, text);
                ps2.setString(6, tt);




                ps= conn.prepareStatement(sql);

                ps2.execute();
                ps.executeUpdate();

                //stmt.close();


                     deamount.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(deposit.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnconfirmMouseClicked

    private void btnexit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexit2MouseClicked

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        userHome uhome=new userHome();
        uhome.setVisible(true);
        uhome.pack();
        uhome.setLocationRelativeTo(null);
        uhome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnconfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseEntered
       setColor(btnconfirm);
    }//GEN-LAST:event_btnconfirmMouseEntered

    private void btnconfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseExited
       resetColor(btnconfirm);
    }//GEN-LAST:event_btnconfirmMouseExited

    private void btncancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseEntered
       setcancelColor(btncancel);
    }//GEN-LAST:event_btncancelMouseEntered

    private void btncancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseExited
        resetcancelColor(btncancel);
    }//GEN-LAST:event_btncancelMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked
       void setColor(JPanel panel)
    {
        panel.setBackground(new Color(48, 63, 159));

    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(63, 81, 181));

    }
      void setcancelColor(JPanel panel)
    {
        panel.setBackground(new Color(194, 24, 91));

    }
    void resetcancelColor(JPanel panel)
    {
        panel.setBackground(new Color(233, 30, 99));

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //</editor-fold>
        //</editor-fold>
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel btnback;
    private javax.swing.JPanel btncancel;
    private javax.swing.JPanel btnconfirm;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JLabel btnexit2;
    private javax.swing.JTextField date;
    private javax.swing.JTextField deamount;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
  private void date() {
       String text=new SimpleDateFormat("yyy/MM/dd",Locale.FRANCE).format(new Date());
       date.setText(text);

    }

    private void time() {
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date d=new Date();
               SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss");
               time.setText(s.format(d));

            }
        }).start();{

        }
    }

}
