/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Phellogen
 */
public class overview extends javax.swing.JFrame {

   Connection conn;
PreparedStatement ps;
ResultSet rs;
Statement stmt;


    public overview() {
        initComponents();
        conn = javaconnect.ConncerDB();
        showData();
         this.setLocationRelativeTo(null);
    }
    
    public String edit;
    private void showData()
    {
        try{
            String sql = "select * from Customer_Data";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            jTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        nrc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnedit = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btndelete = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JLabel();
        btnexit2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jselect = new javax.swing.JComboBox<>();
        Search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setAutoCreateRowSorter(true);
        jTable.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTable.setShowGrid(false);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setAlignmentX(0.0F);
        jTable.setAlignmentY(0.0F);
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable.setGridColor(new java.awt.Color(255, 255, 255));
        jTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable.setRowHeight(30);
        jTable.setSelectionBackground(new java.awt.Color(63, 81, 181));
        jTable.setShowHorizontalLines(false);
        jTable.setShowVerticalLines(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jPanel1.add(jTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 930, 90));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 81, 181));
        jLabel6.setText("Email");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 40));

        email.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        email.setBorder(null);
        email.setSelectionColor(new java.awt.Color(0, 121, 107));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 170, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(63, 81, 181));
        jLabel7.setText("Password");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 100, 40));

        password.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 170, 40));

        nrc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nrc.setBorder(null);
        nrc.setSelectionColor(new java.awt.Color(0, 121, 107));
        jPanel1.add(nrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 170, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(63, 81, 181));
        jLabel16.setText("Phone");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 100, 40));

        phone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        phone.setBorder(null);
        phone.setSelectionColor(new java.awt.Color(0, 121, 107));
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 170, 40));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(63, 81, 181));
        jLabel17.setText("Gender");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 100, 40));

        gender.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gender.setBorder(null);
        gender.setSelectionColor(new java.awt.Color(0, 121, 107));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 170, 40));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(63, 81, 181));
        jLabel18.setText("Date");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 100, 40));

        date.setEditable(false);
        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        date.setBorder(null);
        date.setSelectionColor(new java.awt.Color(0, 121, 107));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 170, 40));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(63, 81, 181));
        jLabel19.setText("ID");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 100, 40));

        Id.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Id.setBorder(null);
        Id.setSelectionColor(new java.awt.Color(0, 121, 107));
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 170, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 81, 181));
        jLabel4.setText("Name");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 100, 40));

        name.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        name.setBorder(null);
        name.setSelectionColor(new java.awt.Color(0, 121, 107));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 170, 40));

        jButton1.setBackground(new java.awt.Color(63, 81, 181));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Search");

        javax.swing.GroupLayout jButton1Layout = new javax.swing.GroupLayout(jButton1);
        jButton1.setLayout(jButton1Layout);
        jButton1Layout.setHorizontalGroup(
            jButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jButton1Layout.setVerticalGroup(
            jButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButton1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, -1, 40));

        btnedit.setBackground(new java.awt.Color(63, 81, 181));
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Edit");

        javax.swing.GroupLayout btneditLayout = new javax.swing.GroupLayout(btnedit);
        btnedit.setLayout(btneditLayout);
        btneditLayout.setHorizontalGroup(
            btneditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btneditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        btneditLayout.setVerticalGroup(
            btneditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btneditLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 100, 40));

        btnrefresh.setBackground(new java.awt.Color(63, 81, 181));
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrefreshMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Refresh");

        javax.swing.GroupLayout btnrefreshLayout = new javax.swing.GroupLayout(btnrefresh);
        btnrefresh.setLayout(btnrefreshLayout);
        btnrefreshLayout.setHorizontalGroup(
            btnrefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnrefreshLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnrefreshLayout.setVerticalGroup(
            btnrefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnrefreshLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 100, 40));

        btndelete.setBackground(new java.awt.Color(63, 81, 181));
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeleteMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Delete");

        javax.swing.GroupLayout btndeleteLayout = new javax.swing.GroupLayout(btndelete);
        btndelete.setLayout(btndeleteLayout);
        btndeleteLayout.setHorizontalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btndeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        btndeleteLayout.setVerticalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndeleteLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 100, 40));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(63, 81, 181));
        jLabel20.setText("NRC");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 100, 40));

        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkback.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 40, 40));

        jPanel2.setBackground(new java.awt.Color(63, 81, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UserData");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 80));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/mwhitemini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel2.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 40, 40));

        btnexit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/mwhiteexit.png"))); // NOI18N
        btnexit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit2MouseClicked(evt);
            }
        });
        jPanel2.add(btnexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 40, 40));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Search by");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 100, 40));

        jselect.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "ID", "Date", "Email", "NRC", "Gender", "Phonenumber", " " }));
        jselect.setBorder(null);
        jPanel2.add(jselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 150, -1));

        Search.setBackground(new java.awt.Color(63, 81, 181));
        Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setBorder(null);
        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 150, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 150, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
         int selectrow = jTable.getSelectedRow();
      String did = (jTable.getModel().getValueAt(selectrow,8).toString());
        
    try {
        String sql = "delete   from Customer_Data where Number='"+did+"'";
        stmt = conn.createStatement();
        int i = stmt.executeUpdate(sql);
        
    } catch (SQLException ex) {
        Logger.getLogger(overview.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    try {
        reID.sortID();
    } catch (SQLException ex) {
        Logger.getLogger(overview.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
         showData();
        Search.setText("");
        name.setText("");
        email.setText("");
        password.setText("");
        gender.setText("");
        date.setText("");
        phone.setText("");
        Id.setText("");
        nrc.setText("");
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        try{
            int row = jTable.getSelectedRow();
            String OnClick = (jTable.getModel().getValueAt(row,0).toString());
            String sql = "select * from Customer_Data where name = '"+OnClick+"'";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next()){
                name.setText(rs.getString("Name"));
                email.setText(rs.getString("Email"));
                password.setText(rs.getString("Password"));
                nrc.setText(rs.getString("NRC"));
                edit = rs.getString("NRC");
                phone.setText(rs.getString("Phone"));
                gender.setText(rs.getString("Gender"));
                date.setText(rs.getString("BD"));
                Id.setText(rs.getString("ID"));
                
                
            }
            
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        try{
            //show7 = rs.getString("NRC");
            String n = name.getText();
            String e = email.getText();
            String p = password.getText();
           
            String ph = phone.getText();
            String g = gender.getText();
            String b = date.getText();
            String i = Id.getText();
           String sql = "update Customer_Data  set Name='"+n+"',Email='"+e+"',Password='"+p+"',Phone='"+ph+"',Gender='"+g+"',BD='"+b+"',ID ='"+i+"'where NRC='"+edit+"'";
            //String sql = "update Customer_Data  set Email='"+e+"' where Name='Yan'";
            
            ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Account Updated!");
            
        }
        catch(SQLException  e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btneditMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         try{
            String selection  = (String)jselect.getSelectedItem();
            String sql = "select  * from Customer_Data where "+selection+" =?";
            ps = conn.prepareStatement(sql);
            ps.setString(1,Search.getText());
            rs = ps.executeQuery();
            jTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
      setColor(btnedit);
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        resetColor(btnedit);
    }//GEN-LAST:event_btneditMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        setColor(jButton1);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
       resetColor(jButton1);
    }//GEN-LAST:event_jButton1MouseExited

    private void btnrefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseEntered
       setColor(btnrefresh);
    }//GEN-LAST:event_btnrefreshMouseEntered

    private void btnrefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseExited
       resetColor(btnrefresh);
    }//GEN-LAST:event_btnrefreshMouseExited

    private void btndeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseEntered
        setColor(btndelete);
    }//GEN-LAST:event_btndeleteMouseEntered

    private void btndeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseExited
        resetColor(btndelete);
    }//GEN-LAST:event_btndeleteMouseExited

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void btnexit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexit2MouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        adminhome ahome=new adminhome();
        ahome.setVisible(true);
        ahome.pack();
        ahome.setLocationRelativeTo(null);
        ahome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked
    
    
     void setColor(JPanel panel)
    {
        panel.setBackground(new Color(48, 63, 159));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(63, 81, 181));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new overview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Search;
    private javax.swing.JLabel btnback;
    private javax.swing.JPanel btndelete;
    private javax.swing.JPanel btnedit;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JLabel btnexit2;
    private javax.swing.JPanel btnrefresh;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gender;
    private javax.swing.JPanel jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    public javax.swing.JComboBox<String> jselect;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nrc;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
