/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.Color;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;
import java.util.Locale;
/**
 *
 * @author Phellogen
 */
public class userlogin extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps,ps1,ps2,ps3;
ResultSet rs,rs2;
static String id,camount,sum1,chtype;
    /**
     * Creates new form userloginrgb(0, 137, 123)
     */
    public userlogin() {
        initComponents();
        conn= javaconnect.ConncerDB();
         induser.setOpaque(true);
        this.setLocationRelativeTo(null);
         //overlay.setBackground(new Color(0,0,0,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblpassword = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btnnext = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JLabel();
        btnexit2 = new javax.swing.JLabel();
        overlay = new javax.swing.JPanel();
        btnback = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lbladmin = new javax.swing.JLabel();
        induser = new javax.swing.JPanel();
        indadmin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(52, 52, 52));
        lblpassword.setText("Password");
        jPanel2.add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 160, -1));

        ID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(52, 52, 52));
        ID.setBorder(null);
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 30));

        jSeparator3.setBackground(new java.awt.Color(52, 52, 52));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 300, 10));

        jSeparator6.setBackground(new java.awt.Color(52, 52, 52));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 300, 10));

        Password.setBorder(null);
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 300, 30));

        jPanel1.setBackground(new java.awt.Color(63, 81, 181));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnext.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnnext.setForeground(new java.awt.Color(255, 255, 255));
        btnnext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnnext.setText("Sign in");
        btnnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnextMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnextMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnextMouseEntered(evt);
            }
        });
        jPanel1.add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 100, 40));

        lblusername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(52, 52, 52));
        lblusername.setText("User ID");
        jPanel2.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, -1));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkmini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel2.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 40));

        btnexit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkexit.png"))); // NOI18N
        btnexit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit2MouseClicked(evt);
            }
        });
        jPanel2.add(btnexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 570, 660));

        overlay.setBackground(new java.awt.Color(63, 81, 181));
        overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/mwhiteback.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        overlay.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 40, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Join your tomorrow with us.");
        overlay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 340, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Warmly welcome your back again.");
        overlay.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 340, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/muserverified.png"))); // NOI18N
        overlay.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 210, 150));

        lbluser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbluser.setForeground(new java.awt.Color(204, 204, 204));
        lbluser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluser.setText("User");
        lbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbluserMouseClicked(evt);
            }
        });
        overlay.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        lbladmin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbladmin.setForeground(new java.awt.Color(204, 204, 204));
        lbladmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladmin.setText("Admin");
        lbladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladminMouseClicked(evt);
            }
        });
        overlay.add(lbladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 40));

        induser.setBackground(new java.awt.Color(255, 255, 255));
        induser.setOpaque(false);
        overlay.add(induser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 5));

        indadmin.setBackground(new java.awt.Color(255, 255, 255));
        indadmin.setOpaque(false);
        overlay.add(indadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 80, 5));

        jLabel6.setBackground(new java.awt.Color(225, 225, 225));
        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sign in");
        overlay.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 340, 80));

        getContentPane().add(overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnextMouseClicked
        
        id = ID.getText();
        String pass =new String(Password.getPassword());
        try{
            String sql = "select * from Customer_Data where ID='"+id+"'";
            ps  = conn.prepareStatement(sql);
            //ps.setString(1, id);
            rs = ps.executeQuery();
            if(rs.next()){
                //String ci = rs.getString("Name");
                String ci = rs.getString("ID");
                System.out.print(ci);
                
                String cp = rs.getString("Password");
                System.out.print(cp);
                if(pass.equals(cp)){
                    ChTransfer();
                    Interest();
                    JOptionPane.showMessageDialog(null, "Login Success");
                     String sql12 = "update Generator set Current_Account='"+id+"' where Count='1'";
                     ps3 = conn.prepareStatement(sql12);
                     ps3.executeUpdate();
                     
                    
                   userHome uhome=new userHome();
                    uhome.setVisible(true);
                    uhome.pack();
                    uhome.setLocationRelativeTo(null);
                    uhome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                    
                    
                }
               
                     
                else{
                    JOptionPane.showMessageDialog(null,"check");
                }
            }
           
            
           
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_btnnextMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        userregister uregister=new userregister();
        uregister.setVisible(true);
        uregister.pack();
        uregister.setLocationRelativeTo(null);
        uregister.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnexit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexit2MouseClicked

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void lbluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbluserMouseClicked
        // TODO add your handling code here:
        induser.setOpaque(true);
        indadmin.setOpaque(false);
        userregister uregister=new userregister();
        uregister.setVisible(true);
        uregister.pack();
        uregister.setLocationRelativeTo(null);
        uregister.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbluserMouseClicked

    private void lbladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladminMouseClicked
        indadmin.setOpaque(true);
        induser.setOpaque(false);
        adminlogin alogin=new adminlogin();
        alogin.setVisible(true);
        alogin.pack();
        alogin.setLocationRelativeTo(null);
        alogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbladminMouseClicked

    private void btnnextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnextMouseEntered
        setColor(jPanel1);
    }//GEN-LAST:event_btnnextMouseEntered

    private void btnnextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnextMouseExited
        resetColor(jPanel1);
    }//GEN-LAST:event_btnnextMouseExited
     void setColor(JPanel panel)
    {
        panel.setBackground(new Color(48, 63, 159));
        
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(63, 81, 181));
        
    }
    
   
    public void Interest() throws SQLException, ParseException{
        String sql2 = "select * from Interest_Data where ID='"+id+"'";
                    ps = conn.prepareStatement(sql2);
                    rs = ps.executeQuery();
                    if(rs.next()){
                        String c = rs.getString("Count");
                        int o = Integer.parseInt(c);
                        if(o==1){
                            String ed = rs.getString("Endtime");
                            
                            Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(ed);
                            String text = new SimpleDateFormat("dd/MM/yyyy", Locale.FRANCE).format(new java.util.Date());
                            Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(text);
                            if(date1.equals(date2)||date2.after(date1))
                            {
                                JOptionPane.showMessageDialog(null,"Your Interest is success");
                                String sql4  = "select * from Customer_Data where ID='"+id+"'";
                                String sql5 = "select * from Interest_Data where ID='"+id+"'";
                                ps1 = conn.prepareStatement(sql5);
                                ps2 = conn.prepareStatement(sql4);
                                rs2 = ps2.executeQuery();
                                rs = ps1.executeQuery();
                                if(rs2.next()){
                                    camount = rs2.getString("Current_Amount");
                                    ps2.close();
                                    rs2.close();
                                }
                                if(rs.next()){
                                    String Inter = rs.getString("Amount");
                                    
                                    int i=Integer.parseInt(Inter);
                                    
                                    int i1=Integer.parseInt(camount);
                                    int sum=i+i1;
                                    sum1=String.valueOf(sum);
                                    ps1.close();
                                }
                                
                                String sql6 = "update Customer_Data set Current_Amount = '"+sum1+"' where ID='"+id+"' ";
                                ps = conn.prepareStatement(sql6);
                                ps.executeUpdate();
                                ps.close();
                                String sql7 = "update Interest_Data set Count='0',Amount='0',Longtime='0',Start_Date='0',Endtime='0' where ID = '"+id+"'";
                                ps = conn.prepareStatement(sql7);
                                ps.executeUpdate();
                                ps.close();
                            }
                            
                        }
                    }
    }
    public void ChTransfer() {
        String sql1 = "select * from Customer_Data where ID='"+id+"'";
                    
  try{
        ps = conn.prepareStatement(sql1);
        rs = ps.executeQuery();
                    if(rs.next()){
                        String c = rs.getString("CT");
                        String r = rs.getString("REC");
                        int ci1 = Integer.parseInt(c);
                        if(ci1==1){
                            JOptionPane.showMessageDialog(null, "Done");
                            JOptionPane.showMessageDialog(null,"You got money from "+r);
                            String sqlu = "update Customer_Data set CT='0',Rec='0' where ID='"+id+"'";
                            ps = conn.prepareStatement(sqlu);
                            ps.executeUpdate();
                            ps.close();
                        }
                    }
    } catch (SQLException ex) {
        Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
    }
                    //ps.setString(1, id);
                    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JLabel btnexit2;
    private javax.swing.JLabel btnnext;
    private javax.swing.JPanel indadmin;
    private javax.swing.JPanel induser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel overlay;
    // End of variables declaration//GEN-END:variables
}
