/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Phellogen
 */
public class userHome extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps,ps1;
ResultSet rs,rs1;
static String ID,show2,show3;
    /**
     * Creates new form userHome
     */
    public userHome() {
        initComponents();
        conn = javaconnect.ConncerDB();
        this.setLocationRelativeTo(null);
              
       try {
           String sql1 = "select * from Generator where Count='1'"; 
           ps  = conn.prepareStatement(sql1);
           rs = ps.executeQuery();
           if(rs.next()){
                
                IDno.setText(rs.getString("Current_Account"));
                ID = rs.getString("Current_Account");
                ps.close();
                rs.close();
           }
       } catch (SQLException ex) {
           Logger.getLogger(withdraw.class.getName()).log(Level.SEVERE, null, ex);
       }
       String sql = "select *from Customer_Data where ID='"+ID+"'";
           String sql1 = "select * from Interest_Data where ID='"+ID+"'";
         
           
        try {
            ps = conn.prepareStatement(sql);
            ps1 = conn.prepareStatement(sql1);
            rs1 = ps1.executeQuery();
            rs = ps.executeQuery();
            if (rs.next()) {

                

                String add2 = rs.getString("Name");
                Name.setText(add2);
               //.setText(ID);
                show2 = rs.getString("Name");
                Current.setText(rs.getString("Current_Amount"));
                String add3 = rs.getString("Email");
                email.setText(add3);
                rs.close();
                ps.close();
            } 
            if(rs1.next()){
                String c = rs1.getString("Count");
             int j = Integer.parseInt(c);
            if(j==1){
                Interest_Type.setText("Your Interest Time");
                show3 = rs1.getString("ENDTIME");
                Show.setText(show3);
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                ps.close();
            } catch (Exception e) {

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bal = new javax.swing.JLabel();
        IDno = new javax.swing.JLabel();
        Current = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnwithdraw = new javax.swing.JPanel();
        indwithdraw = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        withdrawicon = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btntransfer = new javax.swing.JPanel();
        indtransfer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        transfericon = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btndeposit = new javax.swing.JPanel();
        inddeposit = new javax.swing.JPanel();
        Interest_Type = new javax.swing.JLabel();
        depositicon2 = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        btnhistory = new javax.swing.JPanel();
        indhistory = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        historyicon = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(63, 81, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Bal.setForeground(new java.awt.Color(255, 255, 255));
        Bal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bal.setText("Your Balance");
        jPanel1.add(Bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 170, 60));

        IDno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        IDno.setForeground(new java.awt.Color(255, 255, 255));
        IDno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDno.setText("C0018");
        jPanel1.add(IDno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 460, 50));

        Current.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        Current.setForeground(new java.awt.Color(255, 255, 255));
        Current.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Current, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 260, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 460, 150));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Service");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 50, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Terms and conditions");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, -1, -1));

        Logout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(204, 204, 204));
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logout.setText("Sign out");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 110, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("About us");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Home");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        email.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("jhon4233@gmail.com");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 230, -1));

        Name.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Jhon");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 460, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 680));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnwithdraw.setBackground(new java.awt.Color(255, 255, 255));
        btnwithdraw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 240, 241)));
        btnwithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnwithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnwithdrawMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnwithdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnwithdrawMouseExited(evt);
            }
        });
        btnwithdraw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indwithdraw.setBackground(new java.awt.Color(233, 30, 99));
        btnwithdraw.add(indwithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 4));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 52, 52));
        jLabel6.setText("Withdraw");
        btnwithdraw.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        withdrawicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        withdrawicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/withdraw8.png"))); // NOI18N
        btnwithdraw.add(withdrawicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 50, 120));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Remove or take away the amount");
        btnwithdraw.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("from your current balance.");
        btnwithdraw.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel4.add(btnwithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 280, 280));

        btntransfer.setBackground(new java.awt.Color(255, 255, 255));
        btntransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntransferMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntransferMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntransferMouseEntered(evt);
            }
        });
        btntransfer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indtransfer.setBackground(new java.awt.Color(233, 30, 99));
        btntransfer.add(indtransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 4));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 52, 52));
        jLabel4.setText("Transfer");
        btntransfer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, -1));

        transfericon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transfericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/transfer8.png"))); // NOI18N
        btntransfer.add(transfericon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 120));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("to the other you wish.");
        btntransfer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Convey the selected amount");
        btntransfer.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jPanel4.add(btntransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 280, 280));

        btndeposit.setBackground(new java.awt.Color(255, 255, 255));
        btndeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndepositMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndepositMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndepositMouseEntered(evt);
            }
        });
        btndeposit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inddeposit.setBackground(new java.awt.Color(233, 30, 99));
        btndeposit.add(inddeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 4));

        Interest_Type.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Interest_Type.setForeground(new java.awt.Color(52, 52, 52));
        Interest_Type.setText("Interest");
        btndeposit.add(Interest_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        depositicon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/interest.png"))); // NOI18N
        btndeposit.add(depositicon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 60, 130));
        btndeposit.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 40));

        jPanel4.add(btndeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 300, 280));

        btnhistory.setBackground(new java.awt.Color(255, 255, 255));
        btnhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhistoryMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhistoryMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhistoryMouseEntered(evt);
            }
        });
        btnhistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indhistory.setBackground(new java.awt.Color(233, 30, 99));
        btnhistory.add(indhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 4));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 52, 52));
        jLabel7.setText("Deposit");
        btnhistory.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        historyicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/deposit8.png"))); // NOI18N
        btnhistory.add(historyicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 50, 120));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("View all your activities");
        btnhistory.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("in one place.");
        btnhistory.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel4.add(btnhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 300, 280));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkmini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel4.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 40));

        btnexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkexit.png"))); // NOI18N
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        jPanel4.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 720, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitMouseClicked

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void btndepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseEntered
       
        setColor(inddeposit);
       resetColor(indhistory);
       resetColor(indtransfer);
       resetColor(indwithdraw);
    }//GEN-LAST:event_btndepositMouseEntered

    private void btntransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransferMouseEntered
       setColor(indtransfer);
       resetColor(inddeposit);
       resetColor(indhistory);
       resetColor(indwithdraw);
    }//GEN-LAST:event_btntransferMouseEntered

    private void btndepositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseExited
       resetColor(inddeposit);
        resetColor(indhistory);
       resetColor(indtransfer);
       resetColor(indwithdraw);
      
    }//GEN-LAST:event_btndepositMouseExited

    private void btntransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransferMouseExited
       resetColor(inddeposit);
       resetColor(indhistory);
       resetColor(indtransfer);
       resetColor(indwithdraw);
    }//GEN-LAST:event_btntransferMouseExited

    private void btnhistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistoryMouseEntered
        resetColor(inddeposit);
        setColor(indhistory);
       resetColor(indtransfer);
       resetColor(indwithdraw);
    }//GEN-LAST:event_btnhistoryMouseEntered

    private void btnhistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistoryMouseExited
        resetColor(inddeposit);
        resetColor(indhistory);
       resetColor(indtransfer);
       resetColor(indwithdraw);
    }//GEN-LAST:event_btnhistoryMouseExited

    private void btnwithdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwithdrawMouseEntered
       resetColor(inddeposit);
       resetColor(indhistory);
       resetColor(indtransfer);
       setColor(indwithdraw);
    }//GEN-LAST:event_btnwithdrawMouseEntered

    private void btnwithdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwithdrawMouseExited
       resetColor(inddeposit);
       resetColor(indhistory);
       resetColor(indtransfer);
       resetColor(indwithdraw);
    }//GEN-LAST:event_btnwithdrawMouseExited

    private void btnwithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwithdrawMouseClicked
        withdraw w=new withdraw();
        w.setVisible(true);
        w.pack();
        w.setLocationRelativeTo(null);
        w.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnwithdrawMouseClicked

    private void btntransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransferMouseClicked
        transfer t=new transfer();
        t.setVisible(true);
        t.pack();
        t.setLocationRelativeTo(null);
        t.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btntransferMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        String sql = "update Generator set Current_Account='0' where Count='1' ";
    try {
        ps = conn.prepareStatement(sql);
        ps.executeUpdate();
    } catch (SQLException ex) {
        Logger.getLogger(userHome.class.getName()).log(Level.SEVERE, null, ex);
    }
                        userlogin uhome=new userlogin();
                        uhome.setVisible(true);
                        uhome.pack();
                        uhome.setLocationRelativeTo(null);
                        uhome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void btndepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseClicked
        // TODO add your handling code here:
        String sql = "select * from Interest_Data where ID='"+ID+"'";
        
    try {
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        if(rs.next()){
            String c = rs.getString("Count");
             int j = Integer.parseInt(c);
             System.out.print(j);
            if(j==0){
                interest i;
    try {
        i = new  interest();
        i.setVisible(true);
        i.pack();
        i.setLocationRelativeTo(null);
        i.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(userHome.class.getName()).log(Level.SEVERE, null, ex);
    }
            }
            else {
               JOptionPane.showMessageDialog(null, "You cannot do this before your current interest is success!");
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(userHome.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_btndepositMouseClicked

    private void btnhistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistoryMouseClicked
        // TODO add your handling code here:
                         deposit uhome=new deposit();
                        uhome.setVisible(true);
                        uhome.pack();
                        uhome.setLocationRelativeTo(null);
                        uhome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
    }//GEN-LAST:event_btnhistoryMouseClicked
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(233,30,99));
        
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(255,255,255));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bal;
    private javax.swing.JLabel Current;
    private javax.swing.JLabel IDno;
    private javax.swing.JLabel Interest_Type;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Show;
    private javax.swing.JPanel btndeposit;
    private javax.swing.JLabel btnexit;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JPanel btnhistory;
    private javax.swing.JPanel btntransfer;
    private javax.swing.JPanel btnwithdraw;
    private javax.swing.JLabel depositicon2;
    private javax.swing.JLabel email;
    private javax.swing.JLabel historyicon;
    private javax.swing.JPanel inddeposit;
    private javax.swing.JPanel indhistory;
    private javax.swing.JPanel indtransfer;
    private javax.swing.JPanel indwithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel transfericon;
    private javax.swing.JLabel withdrawicon;
    // End of variables declaration//GEN-END:variables
}
