/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import static banking.withdraw.conn;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.server.UID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Date;
import java.util.Locale;
import java.text.SimpleDateFormat;import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
;

/**
 *
 * @author Phellogen
 */
public class withdraw extends javax.swing.JFrame {

   static Connection conn;
    PreparedStatement pst,pst1;
    ResultSet rs;
    static String ID,show2;
    public withdraw() {
        initComponents();
        this.setLocationRelativeTo(null);
        
      
         conn = javaconnect.ConncerDB();
        date1();
        showTime();
            
       try {
           String sql1 = "select * from Generator where Count='1'"; 
           pst  = conn.prepareStatement(sql1);
           rs = pst.executeQuery();
           if(rs.next()){
                
                SID.setText(rs.getString("Current_Account"));
                ID = rs.getString("Current_Account");
           }
       } catch (SQLException ex) {
           Logger.getLogger(withdraw.class.getName()).log(Level.SEVERE, null, ex);
       }
       String sql = "select *from Customer_Data where ID='"+ID+"'";
           
         
           
        try {
            pst = conn.prepareStatement(sql);
          
           
            rs = pst.executeQuery();
            if (rs.next()) {

                

               
                SID.setText(ID);
                show2 = rs.getString("Name");
                
                Camount.setText(rs.getString("Current_Amount"));
                rs.close();
                pst.close();
            } else {
                JOptionPane.showMessageDialog(null, "Enter Correct ID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {

            }
        }
    }
    public void date1() {
        String text = new SimpleDateFormat("yyyy/MM/dd", Locale.FRANCE).format(new Date());
        date.setText(text);
    }
    void showTime(){
    new Timer(0,new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
        
   Date d=new Date();
SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss ");
time.setText(s.format(d));
    }
}).start();
}
    @SuppressWarnings("unchecked")

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblfullname2 = new javax.swing.JLabel();
        Wamount = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnconfirm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JLabel();
        btnexit2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Camount2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bamount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        Camount = new javax.swing.JTextField();
        btnback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1120, 680));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(225, 225, 225));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 52, 52));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Withdraw");
        jLabel2.setEnabled(false);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 820, 50));

        lblfullname2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblfullname2.setForeground(new java.awt.Color(52, 52, 52));
        lblfullname2.setText("Withdraw amount");
        jPanel1.add(lblfullname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 160, -1));

        Wamount.setBackground(new java.awt.Color(246, 246, 246));
        Wamount.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        Wamount.setForeground(new java.awt.Color(52, 52, 52));
        Wamount.setBorder(null);
        Wamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WamountKeyReleased(evt);
            }
        });
        jPanel1.add(Wamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 300, 60));

        jSeparator4.setBackground(new java.awt.Color(52, 52, 52));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 300, 10));

        btnconfirm.setBackground(new java.awt.Color(63, 81, 181));
        btnconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfirmMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirm");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnconfirmLayout = new javax.swing.GroupLayout(btnconfirm);
        btnconfirm.setLayout(btnconfirmLayout);
        btnconfirmLayout.setHorizontalGroup(
            btnconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnconfirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnconfirmLayout.setVerticalGroup(
            btnconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnconfirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 110, 50));

        btnexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkmini.png"))); // NOI18N
        btnexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexit1MousePressed(evt);
            }
        });
        jPanel1.add(btnexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 40));

        btnexit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnexit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkexit.png"))); // NOI18N
        btnexit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexit2MouseClicked(evt);
            }
        });
        jPanel1.add(btnexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 52, 52));
        jLabel7.setText("ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 50));

        SID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SID.setForeground(new java.awt.Color(0, 137, 123));
        SID.setBorder(null);
        jPanel2.add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 50));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("amount");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, 40));

        Camount2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Camount2.setText("Current");
        jPanel2.add(Camount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(63, 81, 181));
        jLabel5.setText("Remaining amount");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 250, 40));

        Bamount.setEditable(false);
        Bamount.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        Bamount.setForeground(new java.awt.Color(63, 81, 181));
        Bamount.setBorder(null);
        jPanel2.add(Bamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 160));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("Time");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 50, 40));

        time.setEditable(false);
        time.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        time.setForeground(new java.awt.Color(63, 81, 181));
        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        time.setBorder(null);
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 150, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Date");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 50, 40));

        date.setEditable(false);
        date.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(63, 81, 181));
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(null);
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 150, 40));

        Camount.setEditable(false);
        Camount.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Camount.setBorder(null);
        jPanel2.add(Camount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 50));

        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/darkback.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseClicked
        //String c = Wamount.getText();
        
        if(Wamount.getText()==null)
        {
            JOptionPane.showMessageDialog(null,"Fill amount");
        }
        else{
        try {
            String a1 = SID.getText();
            String a2 = Bamount.getText();
            String a3 = Wamount.getText();
            String s=date.getText();
            String t = time.getText();
             
           // s1 = jTextField6.getText();
          
           
           
         System.out.print(s);
            System.out.print(a2);
            
            String sql = "update Customer_Data set CURRENT_AMOUNT='"+a2+"' where ID='"+a1+"'";
            String sql2 = "insert into History (ID,Name,Type,Amount,Date,Time)values(?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst1 = conn.prepareStatement(sql2);
             String text = new SimpleDateFormat("yyyy/MM/dd", Locale.FRANCE).format(new Date());
                String tt = time.getText();
                pst1.setString(1,a1);
                pst1.setString(2,show2);
                pst1.setString(3,"WithDraw");
                pst1.setString(4, a3);
                pst1.setString(5, text);
                pst1.setString(6, tt);
            pst1.execute();  
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "WITHDRAW SUCCESSFUL");
           // pst.close();
              //insert();
        } catch (Exception e) {
             if(Bamount.getText()==null&& Wamount.getText()==null){
               JOptionPane.showMessageDialog(null,"Fill the amount");
           } 
            Logger.getLogger(deposit.class.getName()).log(Level.SEVERE, null, e);
        }}
        
    }//GEN-LAST:event_btnconfirmMouseClicked

    private void WamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WamountKeyReleased
       
        
        try {
            String a1 = Camount.getText();
            String a2 = Wamount.getText();
            
            if(a1==null && a2==null){
                JOptionPane.showMessageDialog(null,"You need to fill the amount");
            }
            
            
            
            else  if (Integer.parseInt(a1) < Integer.parseInt(a2)) {
                JOptionPane.showMessageDialog(null, "Your Withdraw Amount is more than your current amount");
               // userHome uh=new userHome();
       // uh.setVisible(true);
        //uh.pack();
      //  uh.setLocationRelativeTo(null);
        //uh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
               
            }

            int sum = Integer.parseInt(a1) - Integer.parseInt(a2);
            String sum1 = String.valueOf(sum);
            Bamount.setText(sum1);

        } catch (Exception e) {
           
        }
        
    }//GEN-LAST:event_WamountKeyReleased

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        userHome uhome=new userHome();
        uhome.setVisible(true);
        uhome.pack();
        uhome.setLocationRelativeTo(null);
        uhome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1MouseClicked

    private void btnexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit1MousePressed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnexit1MousePressed

    private void btnexit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexit2MouseClicked
        // TODO add your handling code here:
         if(Bamount.getText()==null && Wamount.getText()==null){
                JOptionPane.showMessageDialog(null,"Fill the amount");
            }
        this.dispose();
    }//GEN-LAST:event_btnexit2MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        setconfrimcolor(btnconfirm);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        resetconfirmcolor(btnconfirm);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
      
            
            try {
            String a1 = SID.getText();
            String a2 = Bamount.getText();
            String a3 = Wamount.getText();
            String s=date.getText();
            String t = time.getText();
            
           // s1 = jTextField6.getText();
            System.out.print(s);
            System.out.print(a2);
            
            
            
            
            
            String sql = "update Customer_Data set CURRENT_AMOUNT='"+a2+"' where ID='"+a1+"'";
            String sql2 = "insert into History (ID,Name,Type,Amount,Date,Time)values(?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst1 = conn.prepareStatement(sql2);
             String text = new SimpleDateFormat("yyyy/MM/dd", Locale.FRANCE).format(new Date());
                String tt = time.getText();
                pst1.setString(1,a1);
                pst1.setString(2,show2);
                pst1.setString(3,"WithDraw");
                pst1.setString(4, a3);
                pst1.setString(5, text);
                pst1.setString(6, tt);
            pst1.execute();  
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Withdraw successful");
           // pst.close();
            //insert();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked
    void setconfrimcolor(JPanel panel)
    {
        panel.setBackground(new Color(48, 63, 159));
        
    }
    void resetconfirmcolor(JPanel panel)
    {
        panel.setBackground(new Color(63, 81, 181));
        
    }
    
     void setcancelcolor(JPanel panel)
    {
        panel.setBackground(new Color(194, 24, 91));
        
    }
    void resetcancelcolor(JPanel panel)
    {
        panel.setBackground(new Color(233, 30, 99));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bamount;
    private javax.swing.JTextField Camount;
    private javax.swing.JLabel Camount2;
    private javax.swing.JTextField SID;
    private javax.swing.JTextField Wamount;
    private javax.swing.JLabel btnback;
    private javax.swing.JPanel btnconfirm;
    private javax.swing.JLabel btnexit1;
    private javax.swing.JLabel btnexit2;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblfullname2;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
